language: node_js
env:
  - CXX=g++-4.8
node_js:
    - "8"
    - "9"
branches:
    only:
        - master
        - develop
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
  - npm test
before_script:
  - npm run build
after_success:
  - npm run codecov
