language: node_js
node_js:
    - "8"
    - "10"
branches:
    only:
        - master
        - develop
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
script:
  - npm test
before_script:
  - npm run build
after_success:
  - npm run codecov
