language: node_js
env:
  - CXX=g++-4.8
node_js:
    - "6"
    - "5"
    - "4"
branches:
    only:
        - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - $CXX --version
