language: node_js
env:
  - CXX=g++-4.8
node_js:
    - "7"
    - "6"
    - "5"
branches:
    only:
        - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script:
  - npm run build
after_success:
  - npm test
  - npm run codecov
