language: node_js
node_js:
    - "6"
    - "5"
    - "4"
branches:
    only:
        - master
env:
  - CXX=g++-4.8
addons:
  apt:
    packages:
    - g++-4.8
before_install:
    - $CXX --version
install: true
